services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - mssqlConnectionString=Server=mssql;Database=alpha-dashboard;User id=sa;password=${MSSQL_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - mssql
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    networks: 
      - aplha-dashboard-network
    restart: on-failure
    
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - alpha-dashboard-volume:/var/opt/mssql
    networks: 
      - aplha-dashboard-network
    restart: on-failure

networks:
  aplha-dashboard-network:
volumes: 
  alpha-dashboard-volume:
